services:
  sqlserver:
    container_name: container-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: localhost
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Hm](~/880\9I
      MSSQL_PID: Evaluation
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver-data:
