[project]
name = "quant-project"
version = "0.0.1"
dependencies = [
    "pandas",
    "numpy",
    "pyarrow",
    "SQLAlchemy",
    "pyodbc",
    "pydantic",
    "pydantic-settings",
    "streamlit",
    "yfinance",
    "polars>=1.6.0",
    "concurrent-log-handler",
    "dlt",
    "dlt[sqlalchemy]",
    "dlt[mssql]",
]


[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "watchdog", "ipykernel"]


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
app = ["**/*", ".*"]
