[project]
name = "quant-project"
version = "0.0.1"
dependencies = [
    "pandas",
    "numpy",
    "pyarrow",
    "SQLAlchemy",
    "psycopg[binary]",
    "pydantic",
    "pydantic-settings",
    "streamlit",
    "yfinance",
]


[project.optional-dependencies]
dev = ["pytest", "watchdog"]


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
