# https://docs.streamlit.io/develop/api-reference/configuration/config.toml
[browser]
gatherUsageStats = false


[server]
runOnSave = true


[runner]
magicEnabled = false


[theme]
primaryColor = "#0075BE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"
