name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pwd
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          source .venv/bin/activate
          uv sync

      - name: Run tests
        run: |
          pwd
          echo "LOG_LEVEL: ${{ secrets.LOG_LEVEL }}"
          source .venv/bin/activate
          pytest tests/unit
        env:
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          LOG_DIR: ${{ secrets.LOG_DIR }}
          DBT_PROFILES_DIR: ${{ secrets.DBT_PROFILES_DIR }}
          DBT_PROJECT_DIR: ${{ secrets.DBT_PROJECT_DIR }}
