name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          source .venv/bin/activate
          uv sync

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3.5.0
        with:
          args: 
          src: 
            src/
          version:
          version-file:
          checksum:
          github-token: 

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/unit
        env:
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          LOG_DIR: ${{ secrets.LOG_DIR }}
          DBT_PROFILES_DIR: ${{ secrets.DBT_PROFILES_DIR }}
          DBT_PROJECT_DIR: ${{ secrets.DBT_PROJECT_DIR }}
            - name: ruff-action