name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Create .env file
        run: |
          pwd
          echo "LOG_LEVEL=${{ secrets.LOG_LEVEL }}" >> .env
          echo "POSTGRES_URL=${{ secrets.POSTGRES_URL }}" >> .env
          echo "LOG_DIR=${{ secrets.LOG_DIR }}" >> .env
          echo "DBT_PROFILES_DIR=${{ secrets.DBT_PROFILES_DIR }}" >> .env
          echo "DBT_PROJECT_DIR=${{ secrets.DBT_PROJECT_DIR }}" >> .env

      - name: Install dependencies
        run: |
          pwd
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          source .venv/bin/activate
          uv sync

      - name: Run tests
        run: |
          pwd
          source .venv/bin/activate
          pytest tests/unit
