name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pwd
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          source .venv/bin/activate
          uv sync

      - name: Run tests
        run: |
          pwd
          export LOG_LEVEL=${{ secrets.LOG_LEVEL }}
          export POSTGRES_URL=${{ secrets.POSTGRES_URL }}
          export LOG_DIR=${{ secrets.LOG_DIR }}
          export DBT_PROFILES_DIR=${{ secrets.DBT_PROFILES_DIR }}
          export DBT_PROJECT_DIR=${{ secrets.DBT_PROJECT_DIR }}
          source .venv/bin/activate
          pytest tests/unit
